version: '2'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yii2basic
            MYSQL_USER: web
            MYSQL_PASSWORD: web
        ports:
            - "3306:3306"
    nginx:
        image: nginx:latest
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./code:/var/www/code
        ports:
            - "8080:80"
    php:
        build:
            context: ./
            dockerfile: ./conf/php/Dockerfile
        volumes:
            - ./code:/var/www/code